files = main.cpp stream.cpp manage.cpp

all:
	g++-13 -std=c++20 -Wall -I/usr/local/include/opencv4 $(files) -L/usr/lib/aarch64-linux-gnu -lopencv_core -lopencv_highgui -lopencv_videoio -pthread -o main